/**
 * The markdown dialect this application speaks.
 *
 * Deliberately not a dependency. The documents rendered here are generated by
 * this application or written into an agent's own description, so the dialect in
 * play is known and narrow: headings, emphasis, code, lists, tables, quotes,
 * rules and links. Pulling in a full CommonMark parser to cover syntax nothing
 * in the app emits would add weight and another thing to install - and installs
 * are exactly what has hurt on this project.
 *
 * Everything is escaped before any markup is produced, and links are rendered as
 * plain text unless they are http(s), so a hostile agent description cannot
 * inject markup or a javascript: URL into the renderer.
 *
 * It lives in shared rather than beside the component because it is a pure
 * function of text and the part that can go wrong: a parser is worth testing on
 * its own, and this one froze the window once.
 */

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Inline spans, applied to already-escaped text. */
function inline(text: string): string {
  let out = escapeHtml(text)

  // Code first: nothing inside a code span should be interpreted further. The
  // placeholder is a NUL-delimited index, and escapeHtml can never emit a NUL,
  // so prose containing a bare number is never mistaken for a restored span.
  const codes: string[] = []
  out = out.replace(/`([^`]+)`/g, (_m, code: string) => {
    codes.push(code)
    return `\u0000${codes.length - 1}\u0000`
  })

  out = out
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[\s(])\*([^*\n]+)\*/g, '$1<em>$2</em>')
    .replace(/~~([^~]+)~~/g, '<span class="line-through opacity-60">$1</span>')

  // Only http(s) becomes a link; anything else keeps its label as plain text.
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_m, label: string, href: string) =>
    /^https?:\/\//i.test(href)
      ? `<a href="${href}" target="_blank" rel="noreferrer" class="text-accent hover:underline">${label}</a>`
      : label
  )

  return out.replace(
    /\u0000(\d+)\u0000/g,
    (_m, i: string) =>
      `<code class="rounded bg-base-750 px-1 py-0.5 font-mono text-xs text-ink">${escapeHtml(
        codes[Number(i)]
      )}</code>`
  )
}

function renderTable(rows: string[]): string {
  const cells = (line: string): string[] =>
    line
      .replace(/^\||\|$/g, '')
      .split('|')
      .map((c) => c.trim())

  const header = cells(rows[0])
  const body = rows.slice(2).map(cells)

  return [
    '<table class="my-3 w-full border-collapse text-sm">',
    '<thead><tr>',
    ...header.map(
      (h) =>
        `<th class="border-b border-edge px-2 py-1.5 text-left text-2xs uppercase tracking-wider text-ink-faint">${inline(
          h
        )}</th>`
    ),
    '</tr></thead><tbody>',
    ...body.map(
      (row) =>
        `<tr>${row
          .map(
            (c) =>
              `<td class="border-b border-edge/50 px-2 py-1.5 align-top text-ink-dim">${inline(c)}</td>`
          )
          .join('')}</tr>`
    ),
    '</tbody></table>'
  ].join('')
}

export function toHtml(markdown: string): string {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n')
  const out: string[] = []
  let i = 0

  // Every branch below must advance `i`. This enforces it rather than trusting
  // it: if an iteration ends where it began, the next one emits the line as
  // text and steps over it. The renderer has one thread, and a parser that can
  // fail to make progress takes the whole window down with no way to see why.
  let lastIndex = -1

  while (i < lines.length) {
    if (i === lastIndex) {
      out.push(`<p class="my-2 leading-relaxed text-ink-dim">${inline(lines[i])}</p>`)
      i++
      continue
    }
    lastIndex = i

    const line = lines[i]

    // Fenced code
    if (/^```/.test(line)) {
      const body: string[] = []
      i++
      while (i < lines.length && !/^```/.test(lines[i])) body.push(lines[i++])
      i++
      out.push(
        `<pre class="my-3 overflow-x-auto rounded border border-edge bg-base-850 p-3 font-mono text-xs leading-relaxed text-ink-dim">${escapeHtml(
          body.join('\n')
        )}</pre>`
      )
      continue
    }

    // Table: a header row followed by a separator row
    if (/^\s*\|/.test(line) && /^\s*\|[\s:|-]+\|?\s*$/.test(lines[i + 1] ?? '')) {
      const rows: string[] = []
      while (i < lines.length && /^\s*\|/.test(lines[i])) rows.push(lines[i++])
      out.push(renderTable(rows))
      continue
    }

    if (/^\s*(---|\*\*\*|___)\s*$/.test(line)) {
      out.push('<hr class="my-4 border-edge" />')
      i++
      continue
    }

    const heading = line.match(/^(#{1,4})\s+(.*)$/)
    if (heading) {
      const level = heading[1].length
      const sizes = [
        'text-lg font-semibold text-ink mt-5 mb-2',
        'text-base font-semibold text-ink mt-5 mb-2',
        'text-sm font-semibold text-ink mt-4 mb-1.5',
        'text-2xs font-semibold uppercase tracking-wider text-ink-faint mt-4 mb-1'
      ]
      out.push(`<h${level} class="${sizes[level - 1]}">${inline(heading[2])}</h${level}>`)
      i++
      continue
    }

    if (/^\s*>\s?/.test(line)) {
      const body: string[] = []
      while (i < lines.length && /^\s*>\s?/.test(lines[i]))
        body.push(lines[i++].replace(/^\s*>\s?/, ''))
      out.push(
        `<blockquote class="my-3 border-l-2 border-edge-bright pl-3 text-ink-dim">${inline(
          body.join(' ')
        )}</blockquote>`
      )
      continue
    }

    // Lists, bullet or ordered, one level
    if (/^\s*([-*+]|\d+\.)\s+/.test(line)) {
      const ordered = /^\s*\d+\./.test(line)
      const items: string[] = []
      while (i < lines.length && /^\s*([-*+]|\d+\.)\s+/.test(lines[i])) {
        items.push(lines[i++].replace(/^\s*([-*+]|\d+\.)\s+/, ''))
      }
      const tag = ordered ? 'ol' : 'ul'
      out.push(
        `<${tag} class="my-2 ml-4 list-outside space-y-1 ${
          ordered ? 'list-decimal' : 'list-disc'
        } marker:text-ink-faint">${items
          .map((item) => `<li class="text-ink-dim">${inline(item)}</li>`)
          .join('')}</${tag}>`
      )
      continue
    }

    if (!line.trim()) {
      i++
      continue
    }

    // Paragraph: run on until a blank line or a construct starts
    const para: string[] = []
    while (
      i < lines.length &&
      lines[i].trim() &&
      !/^(#{1,4}\s|```|\s*>|\s*([-*+]|\d+\.)\s|\s*\|)/.test(lines[i]) &&
      !/^\s*(---|\*\*\*|___)\s*$/.test(lines[i])
    ) {
      para.push(lines[i++])
    }

    if (para.length) {
      out.push(`<p class="my-2 leading-relaxed text-ink-dim">${inline(para.join(' '))}</p>`)
      continue
    }

    // Nothing consumed this line. That happens when a line looks like the start
    // of a construct but is not one - a row beginning with "|" that has no
    // separator beneath it, say. Emit it as ordinary text and move on.
    //
    // The invariant this protects is the important part: every branch of this
    // loop must advance `i`. Without it a single stray character in a mission
    // statement spins the renderer's only thread forever, and a frozen window
    // is the one failure a user cannot diagnose.
    out.push(`<p class="my-2 leading-relaxed text-ink-dim">${inline(lines[i])}</p>`)
    i++
  }

  return out.join('')
}
